remove secu

diff --git a/.github/workflows/commit-stage.yml b/.github/workflows/commit-stage.yml
--- a/.github/workflows/commit-stage.yml
+++ b/.github/workflows/commit-stage.yml
@@ -8,7 +8,7 @@ env:
 
 jobs:
   build:
-    name: Build and Test
+    name: Build
     runs-on: ubuntu-22.04
     permissions:
       contents: read
@@ -22,32 +22,44 @@ jobs:
           distribution: temurin
           java-version: 17
           cache: gradle
-      - name: Build, unit tests and integration tests
+      - name: Build container image
         run: |
           chmod +x gradlew
-          ./gradlew build
-      - name: Code vulnerability scanning
-        uses: anchore/scan-action@v3
-        id: scan
-        with:
-          path: "${{ github.workspace }}"
-          fail-build: false
-          severity-cutoff: high
-      - name: Upload vulnerability report
-        uses: github/codeql-action/upload-sarif@v3
-        if: success() || failure()
-        with:
-          sarif_file: ${{ steps.scan.outputs.sarif }}
-      - name: Setup tools
-        uses: alexellis/setup-arkade@v3
-      - name: Install tools
-        uses: alexellis/arkade-get@master
-        with:
-          kustomize: latest
-          kubeconform: latest
-      - name: Validate Kubernetes manifests
-        run: |
-          kustomize build k8s | kubeconform --strict -
+          ./gradlew bootBuildImage \
+            --imageName ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
+
+      # - name: Build, unit tests and integration tests
+      #   run: |
+      #     chmod +x gradlew
+      #     ./gradlew build
+
+      # - name: Code vulnerability scanning
+      #   uses: anchore/scan-action@v3
+      #   id: scan
+      #   with:
+      #     path: "${{ github.workspace }}"
+      #     fail-build: false
+      #     severity-cutoff: high
+
+      # - name: Upload vulnerability report
+      #   uses: github/codeql-action/upload-sarif@v3
+      #   if: success() || failure()
+      #   with:
+      #     sarif_file: ${{ steps.scan.outputs.sarif }}
+
+      # - name: Setup tools
+      #   uses: alexellis/setup-arkade@v3
+
+      # - name: Install tools
+      #   uses: alexellis/arkade-get@master
+      #   with:
+      #     kustomize: latest
+      #     kubeconform: latest
+
+      # - name: Validate Kubernetes manifests
+      #   run: |
+      #     kustomize build k8s | kubeconform --strict -
+
   package:
     name: Package and Publish
     if: ${{ github.ref == 'refs/heads/main' }}
@@ -71,18 +83,21 @@ jobs:
           chmod +x gradlew
           ./gradlew bootBuildImage \
             --imageName ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
-      - name: OCI image vulnerability scanning
-        uses: anchore/scan-action@v3
-        id: scan
-        with:
-          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
-          fail-build: false
-          severity-cutoff: high
-      - name: Upload vulnerability report
-        uses: github/codeql-action/upload-sarif@v3
-        if: success() || failure()
-        with:
-          sarif_file: ${{ steps.scan.outputs.sarif }}
+
+      # - name: OCI image vulnerability scanning
+      #   uses: anchore/scan-action@v3
+      #   id: scan
+      #   with:
+      #     image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
+      #     fail-build: false
+      #     severity-cutoff: high
+
+      # - name: Upload vulnerability report
+      #   uses: github/codeql-action/upload-sarif@v3
+      #   if: success() || failure()
+      #   with:
+      #     sarif_file: ${{ steps.scan.outputs.sarif }}
+
       - name: Log into container registry
         uses: docker/login-action@v3
         with:
